### ISSUE TITLE
About 3D-ResNext-101 feature of the MSR-VTT dataset.

### ISSUE THREAD

**Issue by Martin-top** [hobincar/SA-LSTM#10]
Hi,

Why didn't you use the `3D-ResNext-101` feature of the `MSR-VTT` dataset to train the model?

**Comment by hobincar** [comment]
Hi,

I was too lazy to do that experiment. I'll add it when it's possible.

**Comment by hobincar** [comment]
I updated the scores of using 3D-ResNext-101 features for the MSR-VTT dataset.

**Comment by Martin-top** [comment]
Thank you very much for your reply.

I noticed that you extracted the 3D-ResNext-101 feature [here](https://github.com/kenshohara/video-classification-3d-cnn-pytorch), and I've been studying this code for a long time.Unfortunately, I still can't extract features from MSVD and  MSR-VTT datasets correctly.

So, I look forward to your uploading the 3D-ResNext-101 features of MSR-VTT dataset.

I am looking forward to your reply. Thank you very much.

Best wish.

**Comment by xiaoyongbest1234** [comment]
Hi,

I have the same problem, I can't extract the 3D-ResNext-101 feature of MSR-VTT dataset normally.
I hope you can upload your  3D-ResNext-101 features of MSR-VTT dataset.

Thanks.

**Comment by hobincar** [comment]
Hi @Martin-top and @xiaoyongbest1234,

As I slightly modified [the original codes for extracting 3D-ResNext-101 features](https://github.com/kenshohara/video-classification-3d-cnn-pytorch), I uploaded the modified codes at [here](https://github.com/hobincar/video-classification-3d-cnn-pytorch).

Also, for those who cannot extract the features, I just uploaded it at README. Please check it.

**Comment by tonmoay** [comment]
Hi, I am adding a short comment, what was your window size? For example, for each video, how many frames you processed per clip? The stride was 5 (if I am not wrong).

**Comment by hobincar** [comment]
Hi @tonmoay ,
I simply follow the original window size used in training each 3D-CNN. For example, for 3D-ResNeXt-101, the window size is 16, which is chosen by following https://github.com/kenshohara/video-classification-3d-cnn-pytorch.

**Comment by tonmoay** [comment]
Thank you, @hobincar, for the information. May I know exactly which ".pth" file you used to extract the features?

Here is the Drive link of the models: https://drive.google.com/drive/folders/1zvl89AgFAApbH0At-gMuZSeQB_LpNP-M

Can you paste the command line you used?

**Comment by hobincar** [comment]
@tonmoay I lost the command, as it is quite a while ago :(
But I found that there're only `resnext-101-kinetics.pth` and `resnext-101-64f-kinetics.pth` in my folder, so it should be one of them, and I guess the real one is `resnext-101-kinetics.pth`.
