### ISSUE TITLE
about reforcement learning

### ISSUE THREAD

**Issue by tuyunbin** [hobincar/SA-LSTM#13]
Hi, your reproduced work and coding ability are both very good. So, would you consider using reforcement learning as objective function instead of cross entropy like many image captioning methods? I think this would further enhance the performance.

**Comment by hobincar** [comment]
Hi. Thanks for visiting my repo.

Currently, I'm sorry but I don't have any plan for using reinforcement learning to boost the performances. I'll think about it when it's available.
