### ISSUE TITLE
about generated sentences

### ISSUE THREAD

**Issue by tuyunbin** [hobincar/SA-LSTM#4]
Thank you for your awesome code!  When I run the train.py, I can only obtain the scores of four metrics. Thus, I have the question that how can the model generate sentences and store them?

**Comment by hobincar** [comment]
Hi,

I think you can refer to the codes [here](https://github.com/hobincar/SA-LSTM/blob/master/utils.py#L148-L149) for generating sentences given the model and features, and add some codes to log the generated sentence into somewhere like [here](https://github.com/hobincar/SA-LSTM/blob/master/train.py#L109).
