### ISSUE TITLE
can you provide features for extracting MSVD dataset with R(2+1)D and 3D-ResNet?

### ISSUE THREAD

**Issue by AlineAlly** [hobincar/SA-LSTM#5]
Hi, thank you very much for releasing your code.
Can you provide features for extracting `MSVD` dataset with`R(2+1)D` and `3D-ResNet`?

**Comment by hobincar** [comment]
Hi,

I uploaded the 3D-ResNext feature for the MSVD dataset. For the R(2+1)D, I'm sorry but I lost it.

**Comment by AlineAlly** [comment]
Hi, thank you very much for your reply.
I have a question how do you extract features from `MSVD`  or `MSR-VTT` datasets using pre-trained `CNN`, such as `<DATASET>_<NETWORK>.hdf5`?

I noticed that you extracted `MSVD_Inception- v4.hdf5` from [here](https://github.com/hobincar/pytorch-video-feature-extractor), so I am eager to learn from you how to further extract `MSVD_3D-ResNet.hdf5` or `MSVD_R(2+1)D.hdf5`,and use other pre-trained `CNN` to extract its corresponding `<DATASET>_<NETWORK>.hdf5`.

**Comment by hobincar** [comment]
I'm a little bit confused. Are you asking about how to extract features from any arbitrary CNN?

If so, the first thing you have to do is preparing a video that you want to extract features from and pre-trained weights of a CNN model that you want to use. Then, load the pre-trained weights to the model and feed the video as input. By extracting 2D or 3D feature maps from an intermediate layer of the model, you get the features that represent the video.

I think you can also follow the codes in the [repo](https://github.com/hobincar/pytorch-video-feature-extractor) you just mentioned :)

**Comment by AlineAlly** [comment]
I'm sorry I didn't describe what I meant.

I noticed [here ](https://github.com/hobincar/pytorch-video-feature-extractor)that you integrated a lot of `CNN` (e.g. `Inceptionnet-v4`, `VGGNet`, `GoogleNet`, etc.), and I ran this code to get the corresponding file (the suffix of this file is `.hdf5`).

I want to know if I want to extract the `.hdf5` of [R(2+1)D](https://github.com/facebookresearch/VMZ), what should I do? My idea is to integrate [R(2+1)D](https://github.com/facebookresearch/VMZ) into [here](https://github.com/hobincar/pytorch-video-feature-extractor), but I don't know how to operate it. Could you please describe your solution idea?And what do I need to pay attention to?

**Comment by hobincar** [comment]
Ah, extracting `R(2+1)D` features is what you wanted. I got it.

Unfortunately, the `R(2+1)D` model is not a model from which I tried to extract features. I just extracted the features by following the awesome code in [here](https://github.com/facebookresearch/VMZ), not from [there](https://github.com/hobincar/pytorch-video-feature-extractor). Sorry for the confusion.
