### ISSUE TITLE
About the results of your model.

### ISSUE THREAD

**Issue by q-rong** [hobincar/SA-LSTM#7]
Hi,
     Why is your `SA-LSTM(Inception-v4)` model so different from `SA-LSTM[3](Inception-v4)` model in terms of evaluation indicators?

Such as:

`SA-LSTM[3](Inception-v4)`              `BLEU4`(45.3)    `CIDEr`(76.2)    `METEOR`(31.9)   `ROUGE_L`(64.2)
`SA-LSTM[Yours](Inception-v4)`        `BLEU4`(50.2)    `CIDEr`(79.0)    `METEOR`(33.3)   `ROUGE_L`(69.7)

**Comment by hobincar** [comment]
Hi,

I guess the different hyperparameters (e.g. the number of neurons in the temporal attention, etc.) are the keys of different performances. Tuning such hyperparameters sometimes give us considerable improvements.

**Comment by q-rong** [comment]
Thank you very much.
You are a very good researcher.

**Comment by q-rong** [comment]
Hi,
I would like to ask you, how can I better adjust these hyperparameters? What's the trick?Or do we have to try them one by one?
Looking forward to your reply, thank you.
